### ISSUE TITLE
Rename repository from `vKTec-IRC-Code-of-Conduct` to `irc-conduct` or `vktec-irc-conduct`

### ISSUE THREAD

**Issue by spudowiar** [vktec/vktec-irc-conduct#2]
Personally, I find the repository name unnecessarily verbose and long and prefer not to use camel case in repository names.

Discuss. :)

**Comment by vktec** [comment]
I discussed this with @shymega and @zleap, and this was what we settled on, but I do agree that it is rather verbose. Perhaps `vktec-irc-conduct` would be better. Any other thoughts?

**Comment by vktec** [comment]
Having discussed this with @shymega and @zleap privately, I will rename the repository to `vktec-irc-conduct`.
